---
- name: NIM management
  hosts: nimserver
  gather_facts: no
  vars_files:
    - "./vars/nim_master.yaml"
  tasks:
  - name: Output the mksysb list to file ./vars/nim_master.yaml
    include_tasks: tasks/list_mksysb.yaml

    #- name: Display the mksysb images
    #shell: |
    #  cat "./vars/mksysb_list.yaml" 
    #register: mksysb_list
    #delegate_to: 127.0.0.1

  - debug:
      var: lsnim_result.stdout_lines
    delegate_to: 127.0.0.1
      #when: inventory_hostname in groups.nimserver
