---
- name: NIM management
  hosts: nimserver
  gather_facts: no
  vars_files:
    - "./vars/nim_master.yaml"
  tasks:
  - name: Output the mksysb list to file ./vars/mksysb_list.yaml and ./logfile/mksysb_list.json
    include_tasks: tasks/list_mksysb.yaml

  - debug:
      var: lsnim_result.stdout_lines
    delegate_to: 127.0.0.1
