---
- name: Create NIM backup for clients
  hosts: nimserver 
  collections: 
    - ibm.power_aix
  vars_files:
    - "./vars/nim_master.yaml"
    - "./vars/lpp_request.yaml"
  vars:
    cur_time: "{{ ansible_date_time.iso8601_basic_short }}"
  tasks:
  - name: Create LPP source
    vars:
      postfixtime: "_mksysb_{{ cur_time }}"
    nim_resource:
      action: create
      name: "{{ item.key }}"
      object_type: lpp_source
      attributes:
        source: "{{ item.value.lpp_src }}"
        location: "{{ item.value.home }}"
    register: lpp_result 
    loop: "{{ lookup('dict',lpp_name,wantlist=True) }}"
    #when: inventory_hostname == nim_master.name

  - name: Display the result of mksysb
    debug:
      msg: "{{ lpp_result }}"
