---
- name: NIM management
  hosts: nimserver
  gather_facts: no
  vars_files:
    - "./vars/nim_master.yaml"
  tasks:
  - name: Output the savevg list to file ./vars/savevg_list.yaml and ./logfile/savevg_list.json
    include_tasks: tasks/list_savevg.yaml

  - debug:
      var: lsnim_result.stdout_lines
    delegate_to: 127.0.0.1
