---
- name: NIM management
  hosts: nimserver
  gather_facts: no
  vars_files:
    - "./vars/nim_master.yaml"
    - "./vars/savevg_list.yaml"
  tasks:
  - name: Make a list of savevg images in nim server
    include_tasks: tasks/list_savevg.yaml
    
  - name: Check the list savevg images exist
    debug:
      msg: "There is no savevg images in NIM server"
    failed_when: savevg|length == 0

  - pause:
      prompt: |-
        Delete savevg options:
        =====================================
        {% for i in savevg %}
        {{ i.option }} - {{ i.name }}
        {% endfor %}
      echo: yes
    register: result 
    #when: inventory_hostname == nim_master.name
    #delegate_to: localhost

  - set_fact:
      savevg_option: "{{ result.user_input }}"

  - name: display input
    debug:
      msg: "{{ savevg_option|int - 1 }}"
    delegate_to: 127.0.0.1

  - name: Invalid option to delete savevg
    debug:
      msg: "Do not delete savevg image since option invalid (not in menu range)"
    failed_when: savevg_option|int > savevg|length or savevg_option|int == 0
    delegate_to: 127.0.0.1

  - pause:
      prompt: |-
        Do you want to delete {{ savevg[savevg_option|int - 1].name }} (yes/no)?
      echo: yes
    register: boolen_savevg
  
  - name: Start to delete the savevg 
    ibm.power_aix.nim_resource:
      action: delete
      object_type: savevg
      name: "{{ savevg[savevg_option|int - 1].name }}"
    when: boolen_savevg.user_input | bool and savevg_option|int -1 <  savevg|length

  - name: Deny to delete savevg
    debug:
      msg: "Do not delete savevg image since do not choose 'yes' to confirm "
    when: not boolen_savevg.user_input | bool 
  
    #- name: change to readable format
  #
  #  shell: |
  #    cat "./logfile/savevg_list.json" | jq > ./logfile/savevg_list.log
  #  delegate_to: 127.0.0.1

